## Context Broker and Entities

In [1]:
	
###Connect to Context Broker

from ngsildclient import Client, Entity, iso8601

client = Client(hostname="100.85.126.64",port=1026)

Connected to Context Broker at 100.85.126.64:1026 | tenant=N/A | vendor=Orion-LD | version=post-v1.9.0

In [86]:
client.types.list()

['TemperatureSensor', 'videoRecorded']

In [ ]:
entities = client.query(id="videoRecorded")[-1:]
for entity in entities: 
    client.update(entity)

In [38]:
client.get("urn:ngsi-ld:videoRecorded:camera3:camera3_2025_05_28-12_41_15_PM")

{'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera3:camera3_2025_05_28-12_41_15_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 3}, 'inferred': {'type': 'Property', 'value': True}, 'path': {'type': 'Property', 'value': 'camera3_2025_05_28-12_41_15_PM.mp4'}}

In [47]:
entities = client.query(type="videoRecorded")
for entity in entities:
    if entity['path']['value'] is not None:
        print(entity['id'], entity['path']['value'])

urn:ngsi-ld:videoRecorded:camera1:2025_05_23-03_55_26_PM 2025_05_23-03_55_26_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-05_06_54_PM 2025_05_23-05_06_54_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-03_57_30_PM 2025_05_23-03_57_30_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-05_06_53_PM 2025_05_23-05_06_53_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-05_12_05_PM 2025_05_23-05_12_05_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-04_35_05_PM 2025_05_23-04_35_05_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-03_53_53_PM 2025_05_23-03_53_53_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-03_54_12_PM 2025_05_23-03_54_12_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-05_07_57_PM 2025_05_23-05_07_57_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-03_57_02_PM 2025_05_23-03_57_02_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-03_59_07_PM 2025_05_23-03_59_07_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-05_10_42_PM 2025_05_23-05_10_42_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-05_10_53_PM 2025_05_23-05_10_53_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-03_57_57_PM 2025_05_23-03_57_57_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-05_08_41_PM 2025_05_23-05_08_41_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-03_54_50_PM 2025_05_23-03_54_50_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-04_39_37_PM 2025_05_23-04_39_37_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-05_06_46_PM 2025_05_23-05_06_46_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-05_06_45_PM 2025_05_23-05_06_45_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-04_37_32_PM 2025_05_23-04_37_32_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-05_07_26_PM 2025_05_23-05_07_26_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_22_39_PM 2025_05_23-07_22_39_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_20_56_PM 2025_05_23-07_20_56_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_21_22_PM 2025_05_23-07_21_22_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_21_10_PM 2025_05_23-07_21_10_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_22_51_PM 2025_05_23-07_22_51_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-07_20_56_PM 2025_05_23-07_20_56_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-07_21_22_PM 2025_05_23-07_21_22_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-07_30_23_PM 2025_05_23-07_30_23_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-07_30_52_PM 2025_05_23-07_30_52_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-07_31_32_PM 2025_05_23-07_31_32_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-07_31_06_PM 2025_05_23-07_31_06_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-07_30_11_PM 2025_05_23-07_30_11_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_31_25_PM 2025_05_23-07_31_25_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_32_43_PM 2025_05_23-07_32_43_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_30_18_PM 2025_05_23-07_30_18_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_33_04_PM 2025_05_23-07_33_04_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_30_51_PM 2025_05_23-07_30_51_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_31_44_PM 2025_05_23-07_31_44_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_30_48_PM 2025_05_23-07_30_48_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_32_43_PM 2025_05_23-07_32_43_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_33_35_PM 2025_05_23-07_33_35_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_31_46_PM 2025_05_23-07_31_46_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_31_39_PM 2025_05_23-07_31_39_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_32_11_PM 2025_05_23-07_32_11_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_33_14_PM 2025_05_23-07_33_14_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_31_29_PM 2025_05_23-07_31_29_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_31_21_PM 2025_05_23-07_31_21_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_30_34_PM 2025_05_23-07_30_34_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-07_30_10_PM 2025_05_23-07_30_10_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-07_30_50_PM 2025_05_23-07_30_50_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-07_31_09_PM 2025_05_23-07_31_09_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-07_30_11_PM 2025_05_23-07_30_11_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-07_30_13_PM 2025_05_23-07_30_13_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-07_31_38_PM 2025_05_23-07_31_38_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-07_30_51_PM 2025_05_23-07_30_51_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-07_41_40_PM 2025_05_23-07_41_40_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-07_40_39_PM 2025_05_23-07_40_39_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-07_42_32_PM 2025_05_23-07_42_32_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-07_40_25_PM 2025_05_23-07_40_25_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-07_42_09_PM 2025_05_23-07_42_09_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_43_17_PM 2025_05_23-07_43_17_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_40_20_PM 2025_05_23-07_40_20_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_43_07_PM 2025_05_23-07_43_07_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_41_16_PM 2025_05_23-07_41_16_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_41_08_PM 2025_05_23-07_41_08_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_42_34_PM 2025_05_23-07_42_34_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_41_26_PM 2025_05_23-07_41_26_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_42_47_PM 2025_05_23-07_42_47_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_42_23_PM 2025_05_23-07_42_23_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_41_07_PM 2025_05_23-07_41_07_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_43_07_PM 2025_05_23-07_43_07_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_41_30_PM 2025_05_23-07_41_30_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_43_28_PM 2025_05_23-07_43_28_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_42_40_PM 2025_05_23-07_42_40_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_40_34_PM 2025_05_23-07_40_34_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_44_09_PM 2025_05_23-07_44_09_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-07_40_18_PM 2025_05_23-07_40_18_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-07_41_02_PM 2025_05_23-07_41_02_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-07_42_58_PM 2025_05_23-07_42_58_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-07_40_44_PM 2025_05_23-07_40_44_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-07_41_18_PM 2025_05_23-07_41_18_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-07_43_50_PM 2025_05_23-07_43_50_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-07_42_10_PM 2025_05_23-07_42_10_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-07_43_37_PM 2025_05_23-07_43_37_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-07_40_19_PM 2025_05_23-07_40_19_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-07_42_15_PM 2025_05_23-07_42_15_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-07_42_25_PM 2025_05_23-07_42_25_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-07_42_36_PM 2025_05_23-07_42_36_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-07_42_45_PM 2025_05_23-07_42_45_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-07_40_36_PM 2025_05_23-07_40_36_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-07_40_17_PM 2025_05_23-07_40_17_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-07_42_08_PM 2025_05_23-07_42_08_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_02_10_PM 2025_05_23-08_02_10_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_00_49_PM 2025_05_23-08_00_49_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_00_33_PM 2025_05_23-08_00_33_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_01_05_PM 2025_05_23-08_01_05_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_01_16_PM 2025_05_23-08_01_16_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_59_05_PM 2025_05_23-07_59_05_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-08_01_28_PM 2025_05_23-08_01_28_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_59_58_PM 2025_05_23-07_59_58_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-08_00_09_PM 2025_05_23-08_00_09_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-08_00_48_PM 2025_05_23-08_00_48_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-08_00_21_PM 2025_05_23-08_00_21_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_59_44_PM 2025_05_23-07_59_44_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_58_32_PM 2025_05_23-07_58_32_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_58_10_PM 2025_05_23-07_58_10_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-08_01_01_PM 2025_05_23-08_01_01_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-08_00_52_PM 2025_05_23-08_00_52_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-08_00_21_PM 2025_05_23-08_00_21_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_58_46_PM 2025_05_23-07_58_46_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_59_09_PM 2025_05_23-07_59_09_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_58_12_PM 2025_05_23-07_58_12_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_59_40_PM 2025_05_23-07_59_40_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_58_29_PM 2025_05_23-07_58_29_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_58_58_PM 2025_05_23-07_58_58_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_59_32_PM 2025_05_23-07_59_32_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-08_00_06_PM 2025_05_23-08_00_06_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-08_00_53_PM 2025_05_23-08_00_53_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-08_02_02_PM 2025_05_23-08_02_02_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-07_59_57_PM 2025_05_23-07_59_57_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-07_59_07_PM 2025_05_23-07_59_07_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-08_00_34_PM 2025_05_23-08_00_34_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-07_58_11_PM 2025_05_23-07_58_11_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-07_59_46_PM 2025_05_23-07_59_46_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-08_00_15_PM 2025_05_23-08_00_15_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-08_01_04_PM 2025_05_23-08_01_04_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-07_58_54_PM 2025_05_23-07_58_54_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-07_59_32_PM 2025_05_23-07_59_32_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-07_59_42_PM 2025_05_23-07_59_42_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-08_00_01_PM 2025_05_23-08_00_01_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-07_58_18_PM 2025_05_23-07_58_18_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-07_59_27_PM 2025_05_23-07_59_27_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-08_00_28_PM 2025_05_23-08_00_28_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-07_59_11_PM 2025_05_23-07_59_11_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-08_00_16_PM 2025_05_23-08_00_16_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-07_58_09_PM 2025_05_23-07_58_09_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_12_33_PM 2025_05_23-08_12_33_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_11_26_PM 2025_05_23-08_11_26_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_12_24_PM 2025_05_23-08_12_24_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_11_51_PM 2025_05_23-08_11_51_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-08_12_00_PM 2025_05_23-08_12_00_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-08_11_35_PM 2025_05_23-08_11_35_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-08_11_47_PM 2025_05_23-08_11_47_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-08_11_23_PM 2025_05_23-08_11_23_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-08_12_09_PM 2025_05_23-08_12_09_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-08_13_10_PM 2025_05_23-08_13_10_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-08_12_50_PM 2025_05_23-08_12_50_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-08_11_38_PM 2025_05_23-08_11_38_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-08_11_23_PM 2025_05_23-08_11_23_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-08_13_00_PM 2025_05_23-08_13_00_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-08_12_14_PM 2025_05_23-08_12_14_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-08_11_22_PM 2025_05_23-08_11_22_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-08_13_07_PM 2025_05_23-08_13_07_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-08_11_22_PM 2025_05_23-08_11_22_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_16_16_PM 2025_05_23-08_16_16_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_15_21_PM 2025_05_23-08_15_21_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_15_53_PM 2025_05_23-08_15_53_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_16_35_PM 2025_05_23-08_16_35_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_16_46_PM 2025_05_23-08_16_46_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-08_15_27_PM 2025_05_23-08_15_27_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-08_17_08_PM 2025_05_23-08_17_08_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-08_16_10_PM 2025_05_23-08_16_10_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-08_16_52_PM 2025_05_23-08_16_52_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-08_18_00_PM 2025_05_23-08_18_00_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-08_15_44_PM 2025_05_23-08_15_44_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-08_17_25_PM 2025_05_23-08_17_25_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-08_17_13_PM 2025_05_23-08_17_13_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-08_15_58_PM 2025_05_23-08_15_58_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-08_16_22_PM 2025_05_23-08_16_22_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-08_16_39_PM 2025_05_23-08_16_39_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-08_16_06_PM 2025_05_23-08_16_06_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-08_15_44_PM 2025_05_23-08_15_44_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-08_15_36_PM 2025_05_23-08_15_36_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-08_15_21_PM 2025_05_23-08_15_21_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-08_18_33_PM 2025_05_23-08_18_33_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-08_15_54_PM 2025_05_23-08_15_54_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-08_19_03_PM 2025_05_23-08_19_03_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-08_17_10_PM 2025_05_23-08_17_10_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-08_18_54_PM 2025_05_23-08_18_54_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-08_18_36_PM 2025_05_23-08_18_36_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-08_15_49_PM 2025_05_23-08_15_49_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-08_18_18_PM 2025_05_23-08_18_18_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-08_15_27_PM 2025_05_23-08_15_27_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-08_16_10_PM 2025_05_23-08_16_10_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-08_16_40_PM 2025_05_23-08_16_40_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-08_17_14_PM 2025_05_23-08_17_14_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-08_17_44_PM 2025_05_23-08_17_44_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-08_18_27_PM 2025_05_23-08_18_27_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-08_15_55_PM 2025_05_23-08_15_55_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-08_18_47_PM 2025_05_23-08_18_47_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-08_15_41_PM 2025_05_23-08_15_41_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-08_15_20_PM 2025_05_23-08_15_20_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_27_37_PM 2025_05_23-08_27_37_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_28_46_PM 2025_05_23-08_28_46_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_26_38_PM 2025_05_23-08_26_38_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-08_26_46_PM 2025_05_23-08_26_46_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-08_27_50_PM 2025_05_23-08_27_50_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-08_27_25_PM 2025_05_23-08_27_25_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-08_26_03_PM 2025_05_23-08_26_03_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-08_29_00_PM 2025_05_23-08_29_00_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-08_27_48_PM 2025_05_23-08_27_48_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-08_25_58_PM 2025_05_23-08_25_58_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-08_26_37_PM 2025_05_23-08_26_37_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-08_26_48_PM 2025_05_23-08_26_48_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-08_29_11_PM 2025_05_23-08_29_11_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-08_28_04_PM 2025_05_23-08_28_04_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-08_26_09_PM 2025_05_23-08_26_09_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-08_26_27_PM 2025_05_23-08_26_27_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-08_28_02_PM 2025_05_23-08_28_02_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-08_25_55_PM 2025_05_23-08_25_55_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-08_27_49_PM 2025_05_23-08_27_49_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-08_41_39_PM 2025_05_23-08_41_39_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-08_39_50_PM 2025_05_23-08_39_50_PM.mp4
urn:ngsi-ld:videoRecorded:camera2:2025_05_23-08_41_21_PM 2025_05_23-08_41_21_PM.mp4
urn:ngsi-ld:videoRecorded:camera3:2025_05_23-08_40_35_PM 2025_05_23-08_40_35_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-08_41_14_PM 2025_05_23-08_41_14_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-08_41_43_PM 2025_05_23-08_41_43_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-08_41_59_PM 2025_05_23-08_41_59_PM.mp4
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-08_40_15_PM 2025_05_23-08_40_15_PM.mp4
urn:ngsi-ld:videoRecorded:camera5:2025_05_23-08_40_25_PM 2025_05_23-08_40_25_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-08_41_49_PM 2025_05_23-08_41_49_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-08_41_01_PM 2025_05_23-08_41_01_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-08_42_11_PM 2025_05_23-08_42_11_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-08_39_56_PM 2025_05_23-08_39_56_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-08_43_17_PM 2025_05_23-08_43_17_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-08_40_36_PM 2025_05_23-08_40_36_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-08_42_33_PM 2025_05_23-08_42_33_PM.mp4
urn:ngsi-ld:videoRecorded:camera6:2025_05_23-08_41_32_PM 2025_05_23-08_41_32_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_55_46_PM 2025_05_23-08_55_46_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_56_55_PM 2025_05_23-08_56_55_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_54_42_PM 2025_05_23-08_54_42_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_54_58_PM 2025_05_23-08_54_58_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_56_43_PM 2025_05_23-08_56_43_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_54_14_PM 2025_05_23-08_54_14_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_55_34_PM 2025_05_23-08_55_34_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_55_11_PM 2025_05_23-08_55_11_PM.mp4
urn:ngsi-ld:videoRecorded:camera4:2025_05_23-08_56_25_PM 2025_05_23-08_56_25_PM.mp4

In [48]:

# Get all entities of type videoRecorded
client.query(type="videoRecorded")

[{'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera1:2025_05_23-03_55_26_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 1}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-03_55_26_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-03_55_26_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera1:2025_05_23-05_06_54_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 1}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-05_06_54_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-05_06_54_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera1:2025_05_23-03_57_30_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 1}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-03_57_30_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-03_57_30_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera1:2025_05_23-05_06_53_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 1}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-05_06_53_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-05_06_53_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera1:2025_05_23-05_12_05_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 1}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-05_12_05_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-05_12_05_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera1:2025_05_23-04_35_05_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 1}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-04_35_05_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-04_35_05_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera1:2025_05_23-03_53_53_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 1}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-03_53_53_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-03_53_53_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera1:2025_05_23-03_54_12_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 1}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-03_54_12_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-03_54_12_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera1:2025_05_23-05_07_57_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 1}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-05_07_57_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-05_07_57_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera1:2025_05_23-03_57_02_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 1}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-03_57_02_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-03_57_02_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera1:2025_05_23-03_59_07_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 1}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-03_59_07_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-03_59_07_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera1:2025_05_23-05_10_42_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 1}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-05_10_42_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-05_10_42_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera1:2025_05_23-05_10_53_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 1}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-05_10_53_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-05_10_53_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera1:2025_05_23-03_57_57_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 1}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-03_57_57_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-03_57_57_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera1:2025_05_23-05_08_41_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 1}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-05_08_41_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-05_08_41_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera1:2025_05_23-03_54_50_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 1}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-03_54_50_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-03_54_50_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera1:2025_05_23-04_39_37_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 1}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-04_39_37_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-04_39_37_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera1:2025_05_23-05_06_46_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 1}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-05_06_46_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-05_06_46_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera1:2025_05_23-05_06_45_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 1}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-05_06_45_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-05_06_45_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera1:2025_05_23-04_37_32_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 1}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-04_37_32_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-04_37_32_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera1:2025_05_23-05_07_26_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 1}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-05_07_26_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-05_07_26_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_22_39_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 2}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_22_39_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_22_39_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_20_56_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 2}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_20_56_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_20_56_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_21_22_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 2}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_21_22_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_21_22_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_21_10_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 2}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_21_10_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_21_10_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_22_51_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 2}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_22_51_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_22_51_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera1:2025_05_23-07_20_56_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 1}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_20_56_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_20_56_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera1:2025_05_23-07_21_22_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 1}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_21_22_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_21_22_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera4:2025_05_23-07_30_23_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 4}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_30_23_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_30_23_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera4:2025_05_23-07_30_52_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 4}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_30_52_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_30_52_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera4:2025_05_23-07_31_32_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 4}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_31_32_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_31_32_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera4:2025_05_23-07_31_06_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 4}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_31_06_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_31_06_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera4:2025_05_23-07_30_11_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 4}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_30_11_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_30_11_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_31_25_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 2}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_31_25_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_31_25_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_32_43_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 2}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_32_43_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_32_43_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_30_18_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 2}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_30_18_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_30_18_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_33_04_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 2}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_33_04_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_33_04_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_30_51_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 2}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_30_51_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_30_51_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera2:2025_05_23-07_31_44_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 2}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_31_44_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_31_44_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_30_48_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 3}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_30_48_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_30_48_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_32_43_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 3}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_32_43_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_32_43_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_33_35_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 3}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_33_35_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_33_35_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_31_46_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 3}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_31_46_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_31_46_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_31_39_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 3}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_31_39_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_31_39_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_32_11_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 3}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_32_11_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_32_11_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_33_14_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 3}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_33_14_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_33_14_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_31_29_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 3}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_31_29_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_31_29_PM.mp4'}},
 {'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera3:2025_05_23-07_31_21_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 3}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-07_31_21_PM'}, 'inferred': {'type': 'Property', 'value': False}, 'path': {'type': 'Property', 'value': '2025_05_23-07_31_21_PM.mp4'}},

In [49]:
entities = client.query_head(type="videoRecorded")
for entity in entities:
    print(entity.id)
    print(entity.type)
    print(entity['inferred']['value'])
    print(entity['dateObserved']['value'])
    print("-----")

urn:ngsi-ld:videoRecorded:camera1:2025_05_23-03_55_26_PM
videoRecorded
False
2025_05_23-03_55_26_PM
-----
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-05_06_54_PM
videoRecorded
False
2025_05_23-05_06_54_PM
-----
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-03_57_30_PM
videoRecorded
False
2025_05_23-03_57_30_PM
-----
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-05_06_53_PM
videoRecorded
False
2025_05_23-05_06_53_PM
-----
urn:ngsi-ld:videoRecorded:camera1:2025_05_23-05_12_05_PM
videoRecorded
False
2025_05_23-05_12_05_PM
-----

In [51]:
# Get last 10 entities of type videoRecorded
entities = client.query(type="videoRecorded")[-10:]
for entity in entities:
    if entity['inferred']['value'] == False:
        result = client.get(entity.id)
        #print(result)
        print(entity['path']['value'])

camera1_2025_05_27-10_30_49_AM.mp4
camera1_2025_05_27-10_33_44_AM.mp4
camera1_2025_05_27-10_31_55_AM.mp4
camera6_2025_05_27-10_50_00_AM.mp4
camera6_2025_05_27-10_45_35_AM.mp4
camera1_2025_05_27-10_45_40_AM.mp4
camera1_2025_05_27-11_07_16_AM.mp4
camera6_2025_05_27-11_09_52_AM.mp4
camera1_2025_05_27-11_10_43_AM.mp4
camera1_2025_05_27-11_09_17_AM.mp4

In [78]:
#Get video path
entities = client.query(type="videoRecorded")
count = 0
for entity in entities:
    if entity['inferred']['value'] == False and entity['path']['value'] is not None:
        count += 1
        print(entity['path']['value'])

print("Count ", count)

2025_05_23-03_55_26_PM.mp4
2025_05_23-05_06_54_PM.mp4
2025_05_23-03_57_30_PM.mp4
2025_05_23-05_06_53_PM.mp4
2025_05_23-05_12_05_PM.mp4
2025_05_23-04_35_05_PM.mp4
2025_05_23-03_53_53_PM.mp4
2025_05_23-03_54_12_PM.mp4
2025_05_23-05_07_57_PM.mp4
2025_05_23-03_57_02_PM.mp4
2025_05_23-03_59_07_PM.mp4
2025_05_23-05_10_42_PM.mp4
2025_05_23-05_10_53_PM.mp4
2025_05_23-03_57_57_PM.mp4
2025_05_23-05_08_41_PM.mp4
2025_05_23-03_54_50_PM.mp4
2025_05_23-04_39_37_PM.mp4
2025_05_23-05_06_46_PM.mp4
2025_05_23-05_06_45_PM.mp4
2025_05_23-04_37_32_PM.mp4
2025_05_23-05_07_26_PM.mp4
2025_05_23-07_22_39_PM.mp4
2025_05_23-07_20_56_PM.mp4
2025_05_23-07_21_22_PM.mp4
2025_05_23-07_21_10_PM.mp4
2025_05_23-07_22_51_PM.mp4
2025_05_23-07_20_56_PM.mp4
2025_05_23-07_21_22_PM.mp4
2025_05_23-07_30_23_PM.mp4
2025_05_23-07_30_52_PM.mp4
2025_05_23-07_31_32_PM.mp4
2025_05_23-07_31_06_PM.mp4
2025_05_23-07_30_11_PM.mp4
2025_05_23-07_31_25_PM.mp4
2025_05_23-07_32_43_PM.mp4
2025_05_23-07_30_18_PM.mp4
2025_05_23-07_33_04_PM.mp4
2025_05_23-07_30_51_PM.mp4
2025_05_23-07_31_44_PM.mp4
2025_05_23-07_30_48_PM.mp4
2025_05_23-07_32_43_PM.mp4
2025_05_23-07_33_35_PM.mp4
2025_05_23-07_31_46_PM.mp4
2025_05_23-07_31_39_PM.mp4
2025_05_23-07_32_11_PM.mp4
2025_05_23-07_33_14_PM.mp4
2025_05_23-07_31_29_PM.mp4
2025_05_23-07_31_21_PM.mp4
2025_05_23-07_30_34_PM.mp4
2025_05_23-07_30_10_PM.mp4
2025_05_23-07_30_50_PM.mp4
2025_05_23-07_31_09_PM.mp4
2025_05_23-07_30_11_PM.mp4
2025_05_23-07_30_13_PM.mp4
2025_05_23-07_31_38_PM.mp4
2025_05_23-07_30_51_PM.mp4
2025_05_23-07_41_40_PM.mp4
2025_05_23-07_40_39_PM.mp4
2025_05_23-07_42_32_PM.mp4
2025_05_23-07_40_25_PM.mp4
2025_05_23-07_42_09_PM.mp4
2025_05_23-07_43_17_PM.mp4
2025_05_23-07_40_20_PM.mp4
2025_05_23-07_43_07_PM.mp4
2025_05_23-07_41_16_PM.mp4
2025_05_23-07_41_08_PM.mp4
2025_05_23-07_42_34_PM.mp4
2025_05_23-07_41_26_PM.mp4
2025_05_23-07_42_47_PM.mp4
2025_05_23-07_42_23_PM.mp4
2025_05_23-07_41_07_PM.mp4
2025_05_23-07_43_07_PM.mp4
2025_05_23-07_41_30_PM.mp4
2025_05_23-07_43_28_PM.mp4
2025_05_23-07_42_40_PM.mp4
2025_05_23-07_40_34_PM.mp4
2025_05_23-07_44_09_PM.mp4
2025_05_23-07_40_18_PM.mp4
2025_05_23-07_41_02_PM.mp4
2025_05_23-07_42_58_PM.mp4
2025_05_23-07_40_44_PM.mp4
2025_05_23-07_41_18_PM.mp4
2025_05_23-07_43_50_PM.mp4
2025_05_23-07_42_10_PM.mp4
2025_05_23-07_43_37_PM.mp4
2025_05_23-07_40_19_PM.mp4
2025_05_23-07_42_15_PM.mp4
2025_05_23-07_42_25_PM.mp4
2025_05_23-07_42_36_PM.mp4
2025_05_23-07_42_45_PM.mp4
2025_05_23-07_40_36_PM.mp4
2025_05_23-07_40_17_PM.mp4
2025_05_23-07_42_08_PM.mp4
2025_05_23-08_02_10_PM.mp4
2025_05_23-08_00_49_PM.mp4
2025_05_23-08_00_33_PM.mp4
2025_05_23-08_01_05_PM.mp4
2025_05_23-08_01_16_PM.mp4
2025_05_23-07_59_05_PM.mp4
2025_05_23-08_01_28_PM.mp4
2025_05_23-07_59_58_PM.mp4
2025_05_23-08_00_09_PM.mp4
2025_05_23-08_00_48_PM.mp4
2025_05_23-08_00_21_PM.mp4
2025_05_23-07_59_44_PM.mp4
2025_05_23-07_58_32_PM.mp4
2025_05_23-07_58_10_PM.mp4
2025_05_23-08_01_01_PM.mp4
2025_05_23-08_00_52_PM.mp4
2025_05_23-08_00_21_PM.mp4
2025_05_23-07_58_46_PM.mp4
2025_05_23-07_59_09_PM.mp4
2025_05_23-07_58_12_PM.mp4
2025_05_23-07_59_40_PM.mp4
2025_05_23-07_58_29_PM.mp4
2025_05_23-07_58_58_PM.mp4
2025_05_23-07_59_32_PM.mp4
2025_05_23-08_00_06_PM.mp4
2025_05_23-08_00_53_PM.mp4
2025_05_23-08_02_02_PM.mp4
2025_05_23-07_59_57_PM.mp4
2025_05_23-07_59_07_PM.mp4
2025_05_23-08_00_34_PM.mp4
2025_05_23-07_58_11_PM.mp4
2025_05_23-07_59_46_PM.mp4
2025_05_23-08_00_15_PM.mp4
2025_05_23-08_01_04_PM.mp4
2025_05_23-07_58_54_PM.mp4
2025_05_23-07_59_32_PM.mp4
2025_05_23-07_59_42_PM.mp4
2025_05_23-08_00_01_PM.mp4
2025_05_23-07_58_18_PM.mp4
2025_05_23-07_59_27_PM.mp4
2025_05_23-08_00_28_PM.mp4
2025_05_23-07_59_11_PM.mp4
2025_05_23-08_00_16_PM.mp4
2025_05_23-07_58_09_PM.mp4
2025_05_23-08_12_33_PM.mp4
2025_05_23-08_11_26_PM.mp4
2025_05_23-08_12_24_PM.mp4
2025_05_23-08_11_51_PM.mp4
2025_05_23-08_12_00_PM.mp4
2025_05_23-08_11_35_PM.mp4
2025_05_23-08_11_47_PM.mp4
2025_05_23-08_11_23_PM.mp4
2025_05_23-08_12_09_PM.mp4
2025_05_23-08_13_10_PM.mp4
2025_05_23-08_12_50_PM.mp4
2025_05_23-08_11_38_PM.mp4
2025_05_23-08_11_23_PM.mp4
2025_05_23-08_13_00_PM.mp4
2025_05_23-08_12_14_PM.mp4
2025_05_23-08_11_22_PM.mp4
2025_05_23-08_13_07_PM.mp4
2025_05_23-08_11_22_PM.mp4
2025_05_23-08_16_16_PM.mp4
2025_05_23-08_15_21_PM.mp4
2025_05_23-08_15_53_PM.mp4
2025_05_23-08_16_35_PM.mp4
2025_05_23-08_16_46_PM.mp4
2025_05_23-08_15_27_PM.mp4
2025_05_23-08_17_08_PM.mp4
2025_05_23-08_16_10_PM.mp4
2025_05_23-08_16_52_PM.mp4
2025_05_23-08_18_00_PM.mp4
2025_05_23-08_15_44_PM.mp4
2025_05_23-08_17_25_PM.mp4
2025_05_23-08_17_13_PM.mp4
2025_05_23-08_15_58_PM.mp4
2025_05_23-08_16_22_PM.mp4
2025_05_23-08_16_39_PM.mp4
2025_05_23-08_16_06_PM.mp4
2025_05_23-08_15_44_PM.mp4
2025_05_23-08_15_36_PM.mp4
2025_05_23-08_15_21_PM.mp4
2025_05_23-08_18_33_PM.mp4
2025_05_23-08_15_54_PM.mp4
2025_05_23-08_19_03_PM.mp4
2025_05_23-08_17_10_PM.mp4
2025_05_23-08_18_54_PM.mp4
2025_05_23-08_18_36_PM.mp4
2025_05_23-08_15_49_PM.mp4
2025_05_23-08_18_18_PM.mp4
2025_05_23-08_15_27_PM.mp4
2025_05_23-08_16_10_PM.mp4
2025_05_23-08_16_40_PM.mp4
2025_05_23-08_17_14_PM.mp4
2025_05_23-08_17_44_PM.mp4
2025_05_23-08_18_27_PM.mp4
2025_05_23-08_15_55_PM.mp4
2025_05_23-08_18_47_PM.mp4
2025_05_23-08_15_41_PM.mp4
2025_05_23-08_15_20_PM.mp4
2025_05_23-08_27_37_PM.mp4
2025_05_23-08_28_46_PM.mp4
2025_05_23-08_26_38_PM.mp4
2025_05_23-08_26_46_PM.mp4
2025_05_23-08_27_50_PM.mp4
2025_05_23-08_27_25_PM.mp4
2025_05_23-08_26_03_PM.mp4
2025_05_23-08_29_00_PM.mp4
2025_05_23-08_27_48_PM.mp4
2025_05_23-08_25_58_PM.mp4
2025_05_23-08_26_37_PM.mp4
2025_05_23-08_26_48_PM.mp4
2025_05_23-08_29_11_PM.mp4
2025_05_23-08_28_04_PM.mp4
2025_05_23-08_26_09_PM.mp4
2025_05_23-08_26_27_PM.mp4
2025_05_23-08_28_02_PM.mp4
2025_05_23-08_25_55_PM.mp4
2025_05_23-08_27_49_PM.mp4
2025_05_23-08_41_39_PM.mp4
2025_05_23-08_39_50_PM.mp4
2025_05_23-08_41_21_PM.mp4
2025_05_23-08_40_35_PM.mp4
2025_05_23-08_41_14_PM.mp4
2025_05_23-08_41_43_PM.mp4
2025_05_23-08_41_59_PM.mp4
2025_05_23-08_40_15_PM.mp4
2025_05_23-08_40_25_PM.mp4
2025_05_23-08_41_49_PM.mp4
2025_05_23-08_41_01_PM.mp4
2025_05_23-08_42_11_PM.mp4
2025_05_23-08_39_56_PM.mp4
2025_05_23-08_43_17_PM.mp4
2025_05_23-08_40_36_PM.mp4
2025_05_23-08_42_33_PM.mp4
2025_05_23-08_41_32_PM.mp4
2025_05_23-08_55_46_PM.mp4
2025_05_23-08_56_55_PM.mp4
2025_05_23-08_54_42_PM.mp4
2025_05_23-08_54_58_PM.mp4
2025_05_23-08_56_43_PM.mp4
2025_05_23-08_54_14_PM.mp4
2025_05_23-08_55_34_PM.mp4
2025_05_23-08_55_11_PM.mp4
2025_05_23-08_56_25_PM.mp4
2025_05_23-08_56_05_PM.mp4
2025_05_23-08_54_40_PM.mp4
2025_05_23-08_54_27_PM.mp4
2025_05_23-08_56_03_PM.mp4
2025_05_23-08_56_30_PM.mp4
2025_05_23-08_54_22_PM.mp4
2025_05_23-08_54_12_PM.mp4
2025_05_23-08_55_08_PM.mp4
2025_05_23-08_56_42_PM.mp4
2025_05_23-08_56_12_PM.mp4
2025_05_23-08_55_39_PM.mp4
2025_05_23-08_56_30_PM.mp4
2025_05_26-12_46_58_PM.mp4
2025_05_26-12_45_42_PM.mp4
2025_05_26-12_48_02_PM.mp4
2025_05_26-12_48_15_PM.mp4
2025_05_26-12_49_26_PM.mp4
2025_05_26-12_46_18_PM.mp4
2025_05_26-12_48_00_PM.mp4
2025_05_26-12_46_32_PM.mp4
2025_05_26-12_47_16_PM.mp4
2025_05_26-12_47_05_PM.mp4
2025_05_26-12_46_00_PM.mp4
2025_05_26-12_48_24_PM.mp4
2025_05_26-12_47_30_PM.mp4
2025_05_26-12_48_16_PM.mp4
2025_05_26-12_46_36_PM.mp4
2025_05_26-12_48_17_PM.mp4
2025_05_26-12_47_41_PM.mp4
2025_05_26-12_45_57_PM.mp4
2025_05_26-12_48_05_PM.mp4
2025_05_26-12_47_14_PM.mp4
2025_05_26-12_46_09_PM.mp4
2025_05_26-12_49_38_PM.mp4
2025_05_26-12_47_24_PM.mp4
2025_05_26-12_46_14_PM.mp4
2025_05_26-12_46_53_PM.mp4
2025_05_26-12_46_41_PM.mp4
2025_05_26-12_46_04_PM.mp4
2025_05_26-12_47_04_PM.mp4
2025_05_26-12_46_28_PM.mp4
2025_05_26-12_45_37_PM.mp4
2025_05_26-01_18_52_PM.mp4
2025_05_26-01_19_18_PM.mp4
2025_05_26-01_18_28_PM.mp4
2025_05_26-01_24_49_PM.mp4
2025_05_26-01_24_27_PM.mp4
2025_05_26-01_26_09_PM.mp4
2025_05_26-01_34_58_PM.mp4
2025_05_26-01_34_36_PM.mp4
2025_05_26-01_33_07_PM.mp4
2025_05_26-01_35_13_PM.mp4
2025_05_26-01_47_45_PM.mp4
2025_05_26-01_44_52_PM.mp4
2025_05_26-01_48_02_PM.mp4
2025_05_26-01_50_18_PM.mp4
2025_05_26-01_48_55_PM.mp4
2025_05_26-01_48_28_PM.mp4
2025_05_26-01_49_19_PM.mp4
2025_05_26-01_50_39_PM.mp4
2025_05_26-03_20_29_PM.mp4
2025_05_26-03_18_54_PM.mp4
2025_05_26-03_17_55_PM.mp4
2025_05_26-03_39_25_PM.mp4
2025_05_26-03_52_26_PM.mp4
2025_05_26-04_04_26_PM.mp4
2025_05_26-04_05_39_PM.mp4
2025_05_26-04_04_49_PM.mp4
2025_05_26-04_07_02_PM.mp4
camera1_2025_05_26-04_19_19_PM.mp4
2025_05_26-03_54_20_PM.mp4
camera4_2025_05_26-05_11_09_PM.mp4
camera4_2025_05_26-05_11_58_PM.mp4
camera1_2025_05_26-05_10_51_PM.mp4
camera1_2025_05_26-05_14_52_PM.mp4
camera1_2025_05_26-05_14_01_PM.mp4
camera1_2025_05_26-05_12_00_PM.mp4
camera5_2025_05_26-05_12_06_PM.mp4
camera5_2025_05_26-05_12_33_PM.mp4
camera5_2025_05_26-05_10_37_PM.mp4
camera5_2025_05_26-05_11_49_PM.mp4
camera5_2025_05_26-05_11_12_PM.mp4
camera5_2025_05_26-05_10_24_PM.mp4
camera6_2025_05_27-10_32_11_AM.mp4
camera6_2025_05_27-10_30_18_AM.mp4
camera1_2025_05_27-10_30_49_AM.mp4
camera1_2025_05_27-10_33_44_AM.mp4
camera1_2025_05_27-10_31_55_AM.mp4
camera6_2025_05_27-10_50_00_AM.mp4
camera6_2025_05_27-10_45_35_AM.mp4
camera1_2025_05_27-10_45_40_AM.mp4
camera1_2025_05_27-11_07_16_AM.mp4
camera6_2025_05_27-11_09_52_AM.mp4
camera1_2025_05_27-11_10_43_AM.mp4
camera1_2025_05_27-11_09_17_AM.mp4
camera4_2025_05_27-12_18_33_PM.mp4
camera4_2025_05_27-12_16_02_PM.mp4
camera4_2025_05_27-12_17_29_PM.mp4
camera3_2025_05_27-12_16_59_PM.mp4
camera2_2025_05_27-12_14_01_PM.mp4
camera2_2025_05_27-12_17_04_PM.mp4
camera5_2025_05_27-12_14_55_PM.mp4
camera5_2025_05_27-12_14_10_PM.mp4
camera6_2025_05_27-12_14_14_PM.mp4
camera6_2025_05_27-12_15_00_PM.mp4
camera1_2025_05_27-12_15_27_PM.mp4
camera1_2025_05_27-12_13_53_PM.mp4
camera1_2025_05_27-12_16_56_PM.mp4
camera1_2025_05_28-12_41_11_PM.mp4
camera1_2025_05_28-12_42_52_PM.mp4
camera4_2025_05_28-12_41_46_PM.mp4
Count  349

In [ ]:
#Change a given entity to true/false

entity = entities[0]

id = entity['id']
print(id)

entity = client.get(id)
entity['inferred']['value'] = False #can change to  true
print(entity)

urn:ngsi-ld:videoRecorded:camera1:2025_05_23-03_55_26_PM
{'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:videoRecorded:camera1:2025_05_23-03_55_26_PM', 'type': 'videoRecorded', 'camera': {'type': 'Property', 'value': 1}, 'path': {'type': 'Property', 'value': '2025_05_23-03_55_26_PM.mp4'}, 'inferred': {'type': 'Property', 'value': False}, 'dateObserved': {'type': 'Property', 'value': '2025_05_23-03_55_26_PM'}}

In [21]:
inferred_false_entities

[]

In [2]:
def build_entity(sensor: dict) -> Entity:
    e = Entity("TemperatureSensor", f"{sensor['id']}")
    e.obs()
    e.prop("temperature", sensor["temperature"])
    return e

In [8]:
client.get('urn:ngsi-ld:TemperatureSensor:001')

{'@context': 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld', 'id': 'urn:ngsi-ld:TemperatureSensor:001', 'type': 'TemperatureSensor', 'dateObserved': {'type': 'Property', 'value': {'@type': 'DateTime', '@value': '2025-05-23T19:54:28Z'}}, 'temperature': {'type': 'Property', 'value': 17}}

## Database

In [87]:
import pandas as pd
import sqlalchemy as sa

# Reemplaza con tus datos
host = "100.85.126.64"
port = 5434
db = "oasis"
user = "admin"
password = "admin"

# URI de conexión
engine = sa.create_engine(f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{db}")

# Leer tabla completa
table = pd.read_sql("SELECT * FROM detectionsobserved", engine)
print(table)

### Modifying columns
with engine.begin() as conn:
	#conn.execute(sa.text("ALTER TABLE detectionsobserved ADD COLUMN camera_number VARCHAR(7)"))
	#conn.execute(sa.text("ALTER TABLE detectionsobserved ALTER COLUMN camera_number TYPE INTEGER USING camera_number::integer"))
	#conn.execute(sa.text("ALTER TABLE detectionsobserved ALTER COLUMN id TYPE TEXT"))
	table = pd.read_sql("SELECT * FROM detectionsobserved", conn)

print(table)
#print(table.dtypes)

                                       id                          video_path  \
0         camera3_1_2025-05-28 12:41:15_1  camera3_2025_05_28-12_41_15_PM.mp4
1         camera3_1_2025-05-28 12:41:15_2  camera3_2025_05_28-12_41_15_PM.mp4
2         camera3_1_2025-05-28 12:41:15_3  camera3_2025_05_28-12_41_15_PM.mp4
3         camera3_1_2025-05-28 12:41:15_4  camera3_2025_05_28-12_41_15_PM.mp4
4         camera3_1_2025-05-28 12:41:15_5  camera3_2025_05_28-12_41_15_PM.mp4
...                                   ...                                 ...
15895   camera1_1_2025-05-23 17:07:03_294          2025_05_23-05_06_54_PM.mp4
15896  camera1_16_2025-05-23 17:07:03_294          2025_05_23-05_06_54_PM.mp4
15897   camera1_3_2025-05-23 17:07:03_294          2025_05_23-05_06_54_PM.mp4
15898   camera1_1_2025-05-23 17:07:03_295          2025_05_23-05_06_54_PM.mp4
15899  camera1_16_2025-05-23 17:07:03_295          2025_05_23-05_06_54_PM.mp4

                      timestamp detection_id  \
0     2025-05-28 12:41:15+00:00            1
1     2025-05-28 12:41:15+00:00            1
2     2025-05-28 12:41:15+00:00            1
3     2025-05-28 12:41:15+00:00            1
4     2025-05-28 12:41:15+00:00            1
...                         ...          ...
15895 2025-05-23 17:07:03+00:00            1
15896 2025-05-23 17:07:03+00:00           16
15897 2025-05-23 17:07:03+00:00            3
15898 2025-05-23 17:07:03+00:00            1
15899 2025-05-23 17:07:03+00:00           16

                                                                                  bbox  \
0          [296.8210144042969, 652.3793334960938, 175.47198486328125, 162.48193359375]
1         [296.666259765625, 652.3299560546875, 175.0545654296875, 162.41510009765625]
2       [296.70526123046875, 652.3221435546875, 175.08485412597656, 162.4044189453125]
3             [296.5048828125, 652.738037109375, 175.66876220703125, 162.802001953125]
4       [296.15814208984375, 652.8666381835938, 175.35073852539062, 162.9754638671875]
...                                                                                ...
15895    [1007.2886962890625, 928.70361328125, 267.55389404296875, 292.81927490234375]
15896     [1425.75048828125, 1014.775146484375, 164.5113525390625, 125.22149658203125]
15897   [1383.6549072265625, 1015.5125732421875, 246.929931640625, 124.96441650390625]
15898  [1007.4237060546875, 928.5135498046875, 267.30926513671875, 293.23321533203125]
15899   [1425.898681640625, 1014.2772216796875, 166.9051513671875, 126.35980224609375]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    skeleton  \
0                         [[361.9019775390625, 601.504638671875], [0.0, 0.0], [356.73382568359375, 594.863037109375], [0.0, 0.0], [335.61767578125, 597.009521484375], [356.12579345703125, 641.6295776367188], [312.34637451171875, 625.6497192382812], [360.65155029296875, 691.2161254882812], [269.53314208984375, 634.736083984375], [0.0, 0.0], [237.90650939941406, 635.7623901367188], [351.10888671875, 720.0619506835938], [323.1742858886719, 715.7437133789062], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
1                     [[362.151611328125, 601.7926025390625], [0.0, 0.0], [357.0204162597656, 595.1021728515625], [0.0, 0.0], [335.7269287109375, 596.8111572265625], [356.0370788574219, 640.6986083984375], [311.97027587890625, 624.9063110351562], [360.0994873046875, 690.1796264648438], [269.01690673828125, 634.9086303710938], [0.0, 0.0], [237.98675537109375, 635.9063720703125], [351.0224304199219, 718.9434814453125], [322.9879150390625, 714.7124633789062], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
2                                [[362.1357421875, 601.7488403320312], [0.0, 0.0], [357.00286865234375, 595.052490234375], [0.0, 0.0], [335.66656494140625, 596.7533569335938], [355.9970703125, 640.4095458984375], [311.8700866699219, 624.80224609375], [359.5692443847656, 689.3457641601562], [268.8092041015625, 634.99853515625], [0.0, 0.0], [238.01626586914062, 635.8552856445312], [350.8812561035156, 718.5433349609375], [322.839599609375, 714.3616943359375], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
3        [[361.78851318359375, 602.0387573242188], [0.0, 0.0], [357.0058288574219, 595.0783081054688], [0.0, 0.0], [336.0078125, 597.3357543945312], [352.545654296875, 643.221923828125], [312.4426574707031, 627.60791015625], [340.0439147949219, 687.8418579101562], [269.66595458984375, 633.9784545898438], [303.7763977050781, 679.537353515625], [238.0722198486328, 634.3701171875], [350.39794921875, 722.8944702148438], [323.00897216796875, 718.5452880859375], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
4      [[361.902587890625, 602.087890625], [0.0, 0.0], [357.3249206542969, 595.065185546875], [0.0, 0.0], [336.4508972167969, 596.7261962890625], [350.87945556640625, 640.5263061523438], [312.769775390625, 625.5990600585938], [332.54266357421875, 683.3057250976562], [268.9944763183594, 633.193115234375], [290.9494323730469, 672.4736328125], [237.78433227539062, 635.871337890625], [349.2726135253906, 719.9578247070312], [323.14892578125, 715.9227294921875], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ...
15895                                                                                                               [[1118.943603515625, 901.01171875], [1120.6158447265625, 880.6429443359375], [1098.659423828125, 888.3013916015625], [0.0, 0.0], [1036.17431640625, 887.2640380859375], [1108.878662109375, 909.854248046875], [941.6962280273438, 951.2396240234375], [1119.5322265625, 1003.233154296875], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
15896                                                                                                                                                                                                                         [[1355.906494140625, 1012.4713134765625], [1375.4739990234375, 1011.6513671875], [0.0, 0.0], [1419.29345703125, 1049.54638671875], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
15897                                                                                                                                                                                                                                    [[1356.0234375, 1008.5767822265625], [1375.595703125, 1010.53125], [0.0, 0.0], [1413.5318603515625, 1050.977294921875], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
15898                                                                                                            [[1118.7720947265625, 900.8692016601562], [1120.29345703125, 880.6400756835938], [1098.58740234375, 888.2964477539062], [0.0, 0.0], [1036.4088134765625, 887.2816772460938], [1109.216796875, 909.6868896484375], [941.813232421875, 951.1292724609375], [1119.5888671875, 1003.7769775390625], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
15899                                                                                                                                                                                                                        [[1357.1732177734375, 1011.3953857421875], [1377.30859375, 1010.802978515625], [0.0, 0.0], [1419.013916015625, 1048.1881103515625], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]

       camera_number
0                  3
1                  3
2                  3
3                  3
4                  3
...              ...
15895              1
15896              1
15897              1
15898              1
15899              1

[15900 rows x 7 columns]
                                       id                          video_path  \
0         camera3_1_2025-05-28 12:41:15_1  camera3_2025_05_28-12_41_15_PM.mp4
1         camera3_1_2025-05-28 12:41:15_2  camera3_2025_05_28-12_41_15_PM.mp4
2         camera3_1_2025-05-28 12:41:15_3  camera3_2025_05_28-12_41_15_PM.mp4
3         camera3_1_2025-05-28 12:41:15_4  camera3_2025_05_28-12_41_15_PM.mp4
4         camera3_1_2025-05-28 12:41:15_5  camera3_2025_05_28-12_41_15_PM.mp4
...                                   ...                                 ...
15899  camera1_16_2025-05-23 17:07:03_295          2025_05_23-05_06_54_PM.mp4
15900   camera1_3_2025-05-23 17:07:03_295          2025_05_23-05_06_54_PM.mp4
15901   camera1_1_2025-05-23 17:07:03_296          2025_05_23-05_06_54_PM.mp4
15902  camera1_16_2025-05-23 17:07:03_296          2025_05_23-05_06_54_PM.mp4
15903   camera1_3_2025-05-23 17:07:03_296          2025_05_23-05_06_54_PM.mp4

                      timestamp detection_id  \
0     2025-05-28 12:41:15+00:00            1
1     2025-05-28 12:41:15+00:00            1
2     2025-05-28 12:41:15+00:00            1
3     2025-05-28 12:41:15+00:00            1
4     2025-05-28 12:41:15+00:00            1
...                         ...          ...
15899 2025-05-23 17:07:03+00:00           16
15900 2025-05-23 17:07:03+00:00            3
15901 2025-05-23 17:07:03+00:00            1
15902 2025-05-23 17:07:03+00:00           16
15903 2025-05-23 17:07:03+00:00            3

                                                                                 bbox  \
0         [296.8210144042969, 652.3793334960938, 175.47198486328125, 162.48193359375]
1        [296.666259765625, 652.3299560546875, 175.0545654296875, 162.41510009765625]
2      [296.70526123046875, 652.3221435546875, 175.08485412597656, 162.4044189453125]
3            [296.5048828125, 652.738037109375, 175.66876220703125, 162.802001953125]
4      [296.15814208984375, 652.8666381835938, 175.35073852539062, 162.9754638671875]
...                                                                               ...
15899  [1425.898681640625, 1014.2772216796875, 166.9051513671875, 126.35980224609375]
15900  [1381.0230712890625, 1015.0694580078125, 253.782470703125, 126.07220458984375]
15901  [1007.5466918945312, 928.3348388671875, 266.9976806640625, 293.40020751953125]
15902  [1426.048095703125, 1013.4317626953125, 170.0733642578125, 127.69525146484375]
15903         [1381.6953125, 1014.1619873046875, 259.9449462890625, 128.344970703125]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    skeleton  \
0                         [[361.9019775390625, 601.504638671875], [0.0, 0.0], [356.73382568359375, 594.863037109375], [0.0, 0.0], [335.61767578125, 597.009521484375], [356.12579345703125, 641.6295776367188], [312.34637451171875, 625.6497192382812], [360.65155029296875, 691.2161254882812], [269.53314208984375, 634.736083984375], [0.0, 0.0], [237.90650939941406, 635.7623901367188], [351.10888671875, 720.0619506835938], [323.1742858886719, 715.7437133789062], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
1                     [[362.151611328125, 601.7926025390625], [0.0, 0.0], [357.0204162597656, 595.1021728515625], [0.0, 0.0], [335.7269287109375, 596.8111572265625], [356.0370788574219, 640.6986083984375], [311.97027587890625, 624.9063110351562], [360.0994873046875, 690.1796264648438], [269.01690673828125, 634.9086303710938], [0.0, 0.0], [237.98675537109375, 635.9063720703125], [351.0224304199219, 718.9434814453125], [322.9879150390625, 714.7124633789062], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
2                                [[362.1357421875, 601.7488403320312], [0.0, 0.0], [357.00286865234375, 595.052490234375], [0.0, 0.0], [335.66656494140625, 596.7533569335938], [355.9970703125, 640.4095458984375], [311.8700866699219, 624.80224609375], [359.5692443847656, 689.3457641601562], [268.8092041015625, 634.99853515625], [0.0, 0.0], [238.01626586914062, 635.8552856445312], [350.8812561035156, 718.5433349609375], [322.839599609375, 714.3616943359375], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
3        [[361.78851318359375, 602.0387573242188], [0.0, 0.0], [357.0058288574219, 595.0783081054688], [0.0, 0.0], [336.0078125, 597.3357543945312], [352.545654296875, 643.221923828125], [312.4426574707031, 627.60791015625], [340.0439147949219, 687.8418579101562], [269.66595458984375, 633.9784545898438], [303.7763977050781, 679.537353515625], [238.0722198486328, 634.3701171875], [350.39794921875, 722.8944702148438], [323.00897216796875, 718.5452880859375], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
4      [[361.902587890625, 602.087890625], [0.0, 0.0], [357.3249206542969, 595.065185546875], [0.0, 0.0], [336.4508972167969, 596.7261962890625], [350.87945556640625, 640.5263061523438], [312.769775390625, 625.5990600585938], [332.54266357421875, 683.3057250976562], [268.9944763183594, 633.193115234375], [290.9494323730469, 672.4736328125], [237.78433227539062, 635.871337890625], [349.2726135253906, 719.9578247070312], [323.14892578125, 715.9227294921875], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ...
15899                                                                                                                                                                                                                        [[1357.1732177734375, 1011.3953857421875], [1377.30859375, 1010.802978515625], [0.0, 0.0], [1419.013916015625, 1048.1881103515625], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
15900                                                                                                                                                                                                                        [[1356.8372802734375, 1007.782470703125], [1377.978759765625, 1010.0029907226562], [0.0, 0.0], [1414.575439453125, 1050.373046875], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
15901                                                                                                               [[1118.7591552734375, 901.0350341796875], [1120.28515625, 880.5818481445312], [1098.21533203125, 888.2671508789062], [0.0, 0.0], [1035.175537109375, 886.9984130859375], [1108.927978515625, 909.2376708984375], [941.9086303710938, 950.1535034179688], [1119.074462890625, 1002.63671875], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
15902                                                                                                                                                                                                                       [[1354.7576904296875, 1009.0072631835938], [1373.667724609375, 1007.909912109375], [0.0, 0.0], [1414.615966796875, 1045.6650390625], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
15903                                                                                                                                                                                                                   [[1353.309326171875, 1008.0679931640625], [1373.077392578125, 1008.6011352539062], [0.0, 0.0], [1413.0955810546875, 1047.4683837890625], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]

       camera_number
0                  3
1                  3
2                  3
3                  3
4                  3
...              ...
15899              1
15900              1
15901              1
15902              1
15903              1

[15904 rows x 7 columns]

In [88]:
# Add test entry

table = pd.read_sql("SELECT * FROM detectionsobserved", engine)

### Modifying table
with engine.begin() as conn:
	conn.execute(sa.text("""
		INSERT INTO detectionsobserved (id, video_path, timestamp, detection_id, bbox, skeleton, camera_number)
		VALUES (:id, :video_path, :timestamp, :detection_id, :bbox, :skeleton, :camera_number)
	"""), {
		"id": 0,
		"video_path": "thisismypath",
		"timestamp": "2004-10-19 10:23:54+06",
		"detection_id": "det0",
		"bbox": None,
		"skeleton": None,
		"camera_number": "camera0"
	})
	#table = pd.read_sql("SELECT * FROM detectionsobserved", conn)
	row_uploaded = pd.read_sql("SELECT * FROM detectionsobserved WHERE id = 0", conn)

#print(table)
print(row_uploaded)
# Close the connection
#engine.dispose()
# Close the client connection
#client.close()

DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "camera0"
LINE 3: ...h', '2004-10-19 10:23:54+06', 'det0', NULL, NULL, 'camera0')
                                                             ^

[SQL:
		INSERT INTO detectionsobserved (id, video_path, timestamp, detection_id, bbox, skeleton, camera_number)
		VALUES (%(id)s, %(video_path)s, %(timestamp)s, %(detection_id)s, %(bbox)s, %(skeleton)s, %(camera_number)s)
	]
[parameters: {'id': 0, 'video_path': 'thisismypath', 'timestamp': '2004-10-19 10:23:54+06', 'detection_id': 'det0', 'bbox': None, 'skeleton': None, 'camera_number': 'camera0'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)

In [ ]:
# DELETE TEST ENTRY

with engine.begin() as conn:
	#conn.execute(sa.text("DELETE FROM detectionsObserved WHERE id = 0"))
	table = pd.read_sql("SELECT * FROM detectionsobserved", conn)

print(table)

ProgrammingError: (psycopg2.errors.UndefinedFunction) operator does not exist: text = integer
LINE 1: DELETE FROM detectionsObserved WHERE id = 0
                                                ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

[SQL: DELETE FROM detectionsObserved WHERE id = 0]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [ ]:
table.head()
#table.tail()

,id,video_path,timestamp,detection_id,bbox,skeleton,camera_number
0,camera4_2025-05-28 12:42:04_1,camera4_2025_05_28-12_41_46_PM.mp4,2025-05-28 12:42:04+00:00,1,"[9.2637300491333, 296.33660888671875, 18.07864...","[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0...",4
1,camera4_2025-05-28 12:42:05_1,camera4_2025_05_28-12_41_46_PM.mp4,2025-05-28 12:42:05+00:00,1,"[10.61923885345459, 296.62945556640625, 20.799...","[[6.0288848876953125, 248.85894775390625], [0....",4
2,camera4_2025-05-28 12:42:06_1,camera4_2025_05_28-12_41_46_PM.mp4,2025-05-28 12:42:06+00:00,1,"[11.941951751708984, 296.78192138671875, 23.39...","[[6.694666385650635, 247.04818725585938], [0.0...",4
3,camera4_2025-05-28 12:42:07_1,camera4_2025_05_28-12_41_46_PM.mp4,2025-05-28 12:42:07+00:00,1,"[14.38686466217041, 296.0160827636719, 28.3196...","[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0...",4
4,camera4_2025-05-28 12:42:08_1,camera4_2025_05_28-12_41_46_PM.mp4,2025-05-28 12:42:08+00:00,1,"[16.467458724975586, 295.837890625, 32.4930839...","[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0...",4

In [83]:
entities = client.query(type="videoRecorded", q="inferred==true")
count = 0
for entity in entities:
    count += 1
    #print(entity['id'], entity['inferred']['value'])

print("Total inferred entities:", count)

Total inferred entities: 11

In [ ]:
table.tail()

,id,video_path,timestamp,detection_id,bbox,skeleton,camera_number
806,camera3_39_2025-05-28 12:42:05_1509,camera3_2025_05_28-12_41_15_PM.mp4,2025-05-28 12:42:05+00:00,39,"[78.93550872802734, 715.99072265625, 157.5519561767578, 417.1537780761719]","[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [28.90176773071289, 579.017578125], [44.74174118041992, 572.45849609375], [61.9918212890625, 626.9093627929688], [0.0, 0.0], [50.954681396484375, 639.847412109375], [0.0, 0.0], [58.430206298828125, 707.9737548828125], [68.93806457519531, 704.2026977539062], [74.63652038574219, 805.7059326171875], [81.32038116455078, 803.764892578125], [119.67822265625, 890.8216552734375], [119.57206726074219, 885.1642456054688]]",3
807,camera3_39_2025-05-28 12:42:05_1510,camera3_2025_05_28-12_41_15_PM.mp4,2025-05-28 12:42:05+00:00,39,"[78.99683380126953, 717.4356689453125, 157.6648406982422, 419.1881103515625]","[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [16.19831085205078, 586.179931640625], [48.053253173828125, 566.943359375], [33.37657928466797, 646.6622924804688], [89.15985107421875, 602.9667358398438], [0.0, 0.0], [88.83369445800781, 644.9661865234375], [50.34754180908203, 707.15771484375], [70.77375793457031, 699.5267333984375], [71.4708480834961, 802.27099609375], [85.94825744628906, 797.37353515625], [105.17463684082031, 888.359619140625], [116.00067901611328, 883.0929565429688]]",3
808,camera3_39_2025-05-28 12:42:05_1511,camera3_2025_05_28-12_41_15_PM.mp4,2025-05-28 12:42:05+00:00,39,"[79.15137481689453, 718.073974609375, 157.95701599121094, 420.7071228027344]","[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [25.72976303100586, 579.5718383789062], [36.771568298339844, 570.0042724609375], [63.04251480102539, 622.8763427734375], [0.0, 0.0], [71.99974060058594, 609.7493286132812], [0.0, 0.0], [57.816917419433594, 713.9075317382812], [61.529258728027344, 710.33251953125], [86.47200012207031, 812.666748046875], [75.01585388183594, 810.19921875], [128.79302978515625, 892.3302001953125], [102.3299560546875, 886.283203125]]",3
809,camera3_39_2025-05-28 12:42:05_1512,camera3_2025_05_28-12_41_15_PM.mp4,2025-05-28 12:42:05+00:00,39,"[79.08558654785156, 718.5317993164062, 157.82937622070312, 421.8354187011719]","[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [26.558429718017578, 583.3953857421875], [45.43711471557617, 578.3793334960938], [73.95787811279297, 657.3863525390625], [88.52336120605469, 656.254638671875], [0.0, 0.0], [109.17855834960938, 731.4359741210938], [55.35471725463867, 734.155029296875], [68.75526428222656, 731.7279052734375], [77.4530029296875, 825.642333984375], [87.29840087890625, 818.778076171875], [117.87565612792969, 893.1846313476562], [117.17742919921875, 887.7222290039062]]",3
810,camera3_39_2025-05-28 12:42:05_1513,camera3_2025_05_28-12_41_15_PM.mp4,2025-05-28 12:42:05+00:00,39,"[76.83202362060547, 720.131103515625, 153.33583068847656, 418.8889465332031]","[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [36.5185432434082, 584.8687744140625], [51.84032440185547, 582.6689453125], [73.93135070800781, 653.8203125], [89.81764221191406, 655.7963256835938], [0.0, 0.0], [109.43455505371094, 729.911865234375], [57.95622253417969, 729.9188842773438], [68.22501373291016, 728.1934814453125], [75.10334777832031, 818.543212890625], [83.62228393554688, 814.075927734375], [107.9381103515625, 892.1541137695312], [112.48460388183594, 888.7662963867188]]",3

In [ ]:
print(table)

Empty DataFrame
Columns: [id, video_path, timestamp, detection_id, bbox, skeleton, camera_number]
Index: []

In [ ]:
table1 = pd.read_sql("SELECT * FROM detectionsobserved ORDER BY timestamp DESC LIMIT 10", engine)
pd.set_option('display.max_colwidth', None)
table1.head()

,id,video_path,timestamp,detection_id,bbox,skeleton,camera_number
0,camera4_4_2025-05-28 12:42:09_680,camera4_2025_05_28-12_41_46_PM.mp4,2025-05-28 12:42:09+00:00,4,"[618.0272827148438, 890.8321533203125, 316.9698486328125, 366.522705078125]","[[587.4429931640625, 814.6595458984375], [592.0722045898438, 792.3748779296875], [565.8202514648438, 807.477783203125], [0.0, 0.0], [521.9439086914062, 798.9383544921875], [616.4044189453125, 797.0282592773438], [499.93402099609375, 866.602783203125], [676.182373046875, 849.0767822265625], [521.8900756835938, 976.9012451171875], [737.0473022460938, 900.269287109375], [576.2733154296875, 1049.03564453125], [668.0933837890625, 981.4414672851562], [592.0116577148438, 1020.0330810546875], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]",4
1,camera4_4_2025-05-28 12:42:08_658,camera4_2025_05_28-12_41_46_PM.mp4,2025-05-28 12:42:08+00:00,4,"[396.643798828125, 852.4639892578125, 271.6999816894531, 453.94915771484375]","[[351.36639404296875, 718.0703125], [355.56634521484375, 700.117919921875], [334.001953125, 711.7816162109375], [0.0, 0.0], [302.0646667480469, 701.486328125], [387.6248779296875, 701.7434692382812], [294.85369873046875, 765.8673095703125], [441.96490478515625, 748.2286376953125], [322.24658203125, 857.8577270507812], [496.5865173339844, 783.5293579101562], [367.3807678222656, 916.9520874023438], [450.2833251953125, 852.8366088867188], [388.4352722167969, 893.9615478515625], [494.49896240234375, 923.0729370117188], [434.40325927734375, 1000.373779296875], [0.0, 0.0], [0.0, 0.0]]",4
2,camera4_4_2025-05-28 12:42:08_650,camera4_2025_05_28-12_41_46_PM.mp4,2025-05-28 12:42:08+00:00,4,"[338.7896728515625, 819.15283203125, 256.0723571777344, 489.02923583984375]","[[298.595703125, 666.7301635742188], [302.1889343261719, 649.2379150390625], [281.6549377441406, 660.2003784179688], [0.0, 0.0], [248.2258758544922, 650.3541870117188], [334.9671325683594, 656.6404418945312], [240.76043701171875, 710.4115600585938], [383.2813415527344, 707.005859375], [259.8226318359375, 799.7708129882812], [432.1083068847656, 742.0021362304688], [304.236572265625, 854.1177978515625], [386.1541442871094, 805.1160888671875], [327.2680358886719, 840.203369140625], [416.86895751953125, 875.674072265625], [376.90435791015625, 940.153564453125], [442.2337646484375, 946.3033447265625], [436.661865234375, 1017.2747802734375]]",4
3,camera4_4_2025-05-28 12:42:08_654,camera4_2025_05_28-12_41_46_PM.mp4,2025-05-28 12:42:08+00:00,4,"[368.5594482421875, 841.59521484375, 267.49273681640625, 475.18304443359375]","[[325.67169189453125, 696.19580078125], [327.84149169921875, 678.9752807617188], [308.07342529296875, 690.9739379882812], [0.0, 0.0], [274.64227294921875, 683.685302734375], [355.6487121582031, 682.49267578125], [269.2656555175781, 743.7570190429688], [408.98785400390625, 726.489013671875], [288.16741943359375, 832.1085205078125], [468.27923583984375, 769.655029296875], [342.0904235839844, 887.7910766601562], [415.8326110839844, 834.518310546875], [361.46929931640625, 874.455322265625], [458.79486083984375, 908.1773071289062], [425.6563720703125, 984.1905517578125], [0.0, 0.0], [0.0, 0.0]]",4
4,camera4_4_2025-05-28 12:42:08_656,camera4_2025_05_28-12_41_46_PM.mp4,2025-05-28 12:42:08+00:00,4,"[382.2271423339844, 848.2528076171875, 270.04632568359375, 463.49432373046875]","[[340.1262512207031, 707.8753051757812], [342.14727783203125, 689.57421875], [322.7911376953125, 703.3679809570312], [0.0, 0.0], [288.64031982421875, 695.8803100585938], [374.8669738769531, 688.6931762695312], [275.52197265625, 752.9862670898438], [428.3608703613281, 741.3784790039062], [303.33746337890625, 844.2091064453125], [480.9268798828125, 776.38330078125], [354.40960693359375, 902.992431640625], [433.17071533203125, 840.109619140625], [370.376708984375, 882.8822021484375], [469.7275085449219, 909.9995727539062], [431.0594787597656, 988.9342041015625], [496.33978271484375, 977.4757690429688], [493.14105224609375, 1055.1448974609375]]",4

In [ ]:
table2 = pd.read_sql("SELECT * FROM detectionsobserved ORDER BY timestamp ASC LIMIT 10", engine)
table2.head()

,id,video_path,timestamp,detection_id,bbox,skeleton,camera_number
0,camera4_1_2025-05-28 12:41:53_222,camera4_2025_05_28-12_41_46_PM.mp4,2025-05-28 12:41:53+00:00,1,"[10.61923885345459, 296.62945556640625, 20.799...","[[6.0288848876953125, 248.85894775390625], [0....",4
1,camera4_1_2025-05-28 12:41:53_223,camera4_2025_05_28-12_41_46_PM.mp4,2025-05-28 12:41:53+00:00,1,"[11.941951751708984, 296.78192138671875, 23.39...","[[6.694666385650635, 247.04818725585938], [0.0...",4
2,camera4_1_2025-05-28 12:41:53_224,camera4_2025_05_28-12_41_46_PM.mp4,2025-05-28 12:41:53+00:00,1,"[14.38686466217041, 296.0160827636719, 28.3196...","[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0...",4
3,camera4_1_2025-05-28 12:41:53_225,camera4_2025_05_28-12_41_46_PM.mp4,2025-05-28 12:41:53+00:00,1,"[16.467458724975586, 295.837890625, 32.4930839...","[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0...",4
4,camera4_1_2025-05-28 12:41:53_226,camera4_2025_05_28-12_41_46_PM.mp4,2025-05-28 12:41:53+00:00,1,"[18.168703079223633, 296.1634216308594, 35.853...","[[10.144001007080078, 248.19822692871094], [0....",4

In [ ]:
#WILL DELETE ALL ENTRIES IN TABLE

with engine.begin() as conn:
    #conn.execute(sa.text("DELETE FROM detectionsobserved"))

In [ ]:
print(table)

                                      id                          video_path  \
0        camera3_1_2025-05-28 12:41:15_1  camera3_2025_05_28-12_41_15_PM.mp4
1        camera3_1_2025-05-28 12:41:15_2  camera3_2025_05_28-12_41_15_PM.mp4
2        camera3_1_2025-05-28 12:41:15_3  camera3_2025_05_28-12_41_15_PM.mp4
3        camera3_1_2025-05-28 12:41:15_4  camera3_2025_05_28-12_41_15_PM.mp4
4        camera3_1_2025-05-28 12:41:15_5  camera3_2025_05_28-12_41_15_PM.mp4
..                                   ...                                 ...
806  camera3_39_2025-05-28 12:42:05_1509  camera3_2025_05_28-12_41_15_PM.mp4
807  camera3_39_2025-05-28 12:42:05_1510  camera3_2025_05_28-12_41_15_PM.mp4
808  camera3_39_2025-05-28 12:42:05_1511  camera3_2025_05_28-12_41_15_PM.mp4
809  camera3_39_2025-05-28 12:42:05_1512  camera3_2025_05_28-12_41_15_PM.mp4
810  camera3_39_2025-05-28 12:42:05_1513  camera3_2025_05_28-12_41_15_PM.mp4

                    timestamp detection_id  \
0   2025-05-28 12:41:15+00:00            1
1   2025-05-28 12:41:15+00:00            1
2   2025-05-28 12:41:15+00:00            1
3   2025-05-28 12:41:15+00:00            1
4   2025-05-28 12:41:15+00:00            1
..                        ...          ...
806 2025-05-28 12:42:05+00:00           39
807 2025-05-28 12:42:05+00:00           39
808 2025-05-28 12:42:05+00:00           39
809 2025-05-28 12:42:05+00:00           39
810 2025-05-28 12:42:05+00:00           39

                                                                               bbox  \
0       [296.8210144042969, 652.3793334960938, 175.47198486328125, 162.48193359375]
1      [296.666259765625, 652.3299560546875, 175.0545654296875, 162.41510009765625]
2    [296.70526123046875, 652.3221435546875, 175.08485412597656, 162.4044189453125]
3          [296.5048828125, 652.738037109375, 175.66876220703125, 162.802001953125]
4    [296.15814208984375, 652.8666381835938, 175.35073852539062, 162.9754638671875]
..                                                                              ...
806      [78.93550872802734, 715.99072265625, 157.5519561767578, 417.1537780761719]
807    [78.99683380126953, 717.4356689453125, 157.6648406982422, 419.1881103515625]
808    [79.15137481689453, 718.073974609375, 157.95701599121094, 420.7071228027344]
809   [79.08558654785156, 718.5317993164062, 157.82937622070312, 421.8354187011719]
810    [76.83202362060547, 720.131103515625, 153.33583068847656, 418.8889465332031]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            skeleton  \
0                                 [[361.9019775390625, 601.504638671875], [0.0, 0.0], [356.73382568359375, 594.863037109375], [0.0, 0.0], [335.61767578125, 597.009521484375], [356.12579345703125, 641.6295776367188], [312.34637451171875, 625.6497192382812], [360.65155029296875, 691.2161254882812], [269.53314208984375, 634.736083984375], [0.0, 0.0], [237.90650939941406, 635.7623901367188], [351.10888671875, 720.0619506835938], [323.1742858886719, 715.7437133789062], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
1                             [[362.151611328125, 601.7926025390625], [0.0, 0.0], [357.0204162597656, 595.1021728515625], [0.0, 0.0], [335.7269287109375, 596.8111572265625], [356.0370788574219, 640.6986083984375], [311.97027587890625, 624.9063110351562], [360.0994873046875, 690.1796264648438], [269.01690673828125, 634.9086303710938], [0.0, 0.0], [237.98675537109375, 635.9063720703125], [351.0224304199219, 718.9434814453125], [322.9879150390625, 714.7124633789062], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
2                                        [[362.1357421875, 601.7488403320312], [0.0, 0.0], [357.00286865234375, 595.052490234375], [0.0, 0.0], [335.66656494140625, 596.7533569335938], [355.9970703125, 640.4095458984375], [311.8700866699219, 624.80224609375], [359.5692443847656, 689.3457641601562], [268.8092041015625, 634.99853515625], [0.0, 0.0], [238.01626586914062, 635.8552856445312], [350.8812561035156, 718.5433349609375], [322.839599609375, 714.3616943359375], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
3                [[361.78851318359375, 602.0387573242188], [0.0, 0.0], [357.0058288574219, 595.0783081054688], [0.0, 0.0], [336.0078125, 597.3357543945312], [352.545654296875, 643.221923828125], [312.4426574707031, 627.60791015625], [340.0439147949219, 687.8418579101562], [269.66595458984375, 633.9784545898438], [303.7763977050781, 679.537353515625], [238.0722198486328, 634.3701171875], [350.39794921875, 722.8944702148438], [323.00897216796875, 718.5452880859375], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
4              [[361.902587890625, 602.087890625], [0.0, 0.0], [357.3249206542969, 595.065185546875], [0.0, 0.0], [336.4508972167969, 596.7261962890625], [350.87945556640625, 640.5263061523438], [312.769775390625, 625.5990600585938], [332.54266357421875, 683.3057250976562], [268.9944763183594, 633.193115234375], [290.9494323730469, 672.4736328125], [237.78433227539062, 635.871337890625], [349.2726135253906, 719.9578247070312], [323.14892578125, 715.9227294921875], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
..                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ...
806                                     [[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [28.90176773071289, 579.017578125], [44.74174118041992, 572.45849609375], [61.9918212890625, 626.9093627929688], [0.0, 0.0], [50.954681396484375, 639.847412109375], [0.0, 0.0], [58.430206298828125, 707.9737548828125], [68.93806457519531, 704.2026977539062], [74.63652038574219, 805.7059326171875], [81.32038116455078, 803.764892578125], [119.67822265625, 890.8216552734375], [119.57206726074219, 885.1642456054688]]
807           [[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [16.19831085205078, 586.179931640625], [48.053253173828125, 566.943359375], [33.37657928466797, 646.6622924804688], [89.15985107421875, 602.9667358398438], [0.0, 0.0], [88.83369445800781, 644.9661865234375], [50.34754180908203, 707.15771484375], [70.77375793457031, 699.5267333984375], [71.4708480834961, 802.27099609375], [85.94825744628906, 797.37353515625], [105.17463684082031, 888.359619140625], [116.00067901611328, 883.0929565429688]]
808                                     [[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [25.72976303100586, 579.5718383789062], [36.771568298339844, 570.0042724609375], [63.04251480102539, 622.8763427734375], [0.0, 0.0], [71.99974060058594, 609.7493286132812], [0.0, 0.0], [57.816917419433594, 713.9075317382812], [61.529258728027344, 710.33251953125], [86.47200012207031, 812.666748046875], [75.01585388183594, 810.19921875], [128.79302978515625, 892.3302001953125], [102.3299560546875, 886.283203125]]
809  [[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [26.558429718017578, 583.3953857421875], [45.43711471557617, 578.3793334960938], [73.95787811279297, 657.3863525390625], [88.52336120605469, 656.254638671875], [0.0, 0.0], [109.17855834960938, 731.4359741210938], [55.35471725463867, 734.155029296875], [68.75526428222656, 731.7279052734375], [77.4530029296875, 825.642333984375], [87.29840087890625, 818.778076171875], [117.87565612792969, 893.1846313476562], [117.17742919921875, 887.7222290039062]]
810            [[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [36.5185432434082, 584.8687744140625], [51.84032440185547, 582.6689453125], [73.93135070800781, 653.8203125], [89.81764221191406, 655.7963256835938], [0.0, 0.0], [109.43455505371094, 729.911865234375], [57.95622253417969, 729.9188842773438], [68.22501373291016, 728.1934814453125], [75.10334777832031, 818.543212890625], [83.62228393554688, 814.075927734375], [107.9381103515625, 892.1541137695312], [112.48460388183594, 888.7662963867188]]

     camera_number
0                3
1                3
2                3
3                3
4                3
..             ...
806              3
807              3
808              3
809              3
810              3

[811 rows x 7 columns]

## Testing Essentials (database)

In [4]:
import pandas as pd
import sqlalchemy as sa

# Reemplaza con tus datos
host = "100.85.126.64"
port = 5434
db = "oasis"
user = "admin"
password = "admin"

# URI de conexión
engine = sa.create_engine(f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{db}")

# Leer tabla completa
table = pd.read_sql("SELECT * FROM detectionsobserved", engine)
#print(table)

In [2]:
entities = client.query(type="videoRecorded", q="inferred==true")
count = 0
for entity in entities:
    count += 1
    #print(entity['id'], entity['inferred']['value'])

print("Total inferred entities:", count)

Total inferred entities: 342

In [91]:
table = pd.read_sql("SELECT * FROM detectionsobserved", engine)
#print(table)
table.tail()

,id,video_path,timestamp,detection_id,bbox,skeleton,camera_number
17529,camera1_3_2025-05-23 17:06:55_61,2025_05_23-05_06_53_PM.mp4,2025-05-23 17:06:55+00:00,3,"[1308.6708984375, 970.7095947265625, 259.1207275390625, 210.73291015625]","[[1305.8017578125, 968.3142700195312], [1331.1893310546875, 961.9117431640625], [1300.8814697265625, 942.2218017578125], [1368.1197509765625, 963.099365234375], [0.0, 0.0], [1401.23681640625, 1045.2447509765625], [1254.270751953125, 956.8533935546875], [0.0, 0.0], [1196.0556640625, 1036.40966796875], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]",1
17530,camera1_1_2025-05-23 17:06:55_62,2025_05_23-05_06_53_PM.mp4,2025-05-23 17:06:55+00:00,1,"[984.290283203125, 945.014892578125, 350.62286376953125, 259.80413818359375]","[[1128.7305908203125, 938.55029296875], [1130.697998046875, 916.919677734375], [1108.07568359375, 922.952880859375], [0.0, 0.0], [1043.6700439453125, 921.2532348632812], [1128.977294921875, 958.199951171875], [954.5963745117188, 967.2313232421875], [0.0, 0.0], [845.9866333007812, 1051.281494140625], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]",1
17531,camera1_3_2025-05-23 17:06:55_62,2025_05_23-05_06_53_PM.mp4,2025-05-23 17:06:55+00:00,3,"[1309.42578125, 970.523681640625, 259.4962158203125, 210.922607421875]","[[1308.496337890625, 968.7804565429688], [1333.5499267578125, 961.9111328125], [1302.9781494140625, 942.914794921875], [1370.014404296875, 962.0994873046875], [0.0, 0.0], [1402.1668701171875, 1042.281005859375], [1255.93701171875, 956.578857421875], [0.0, 0.0], [1199.00732421875, 1037.187255859375], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]",1
17532,camera1_1_2025-05-23 17:06:55_63,2025_05_23-05_06_53_PM.mp4,2025-05-23 17:06:55+00:00,1,"[986.7042236328125, 945.0381469726562, 344.30377197265625, 259.6004638671875]","[[1130.4017333984375, 939.2763061523438], [1131.031005859375, 918.2847900390625], [1109.989501953125, 924.84716796875], [0.0, 0.0], [1045.766357421875, 924.797607421875], [1127.6690673828125, 958.8795166015625], [954.3070678710938, 970.6322021484375], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]",1
17533,camera1_3_2025-05-23 17:06:55_63,2025_05_23-05_06_53_PM.mp4,2025-05-23 17:06:55+00:00,3,"[1310.78955078125, 970.392333984375, 258.541015625, 210.84326171875]","[[1307.212890625, 966.8018798828125], [1332.2747802734375, 960.8311157226562], [1303.048828125, 941.59716796875], [1370.968505859375, 960.8587646484375], [0.0, 0.0], [1404.081298828125, 1042.47314453125], [1257.8238525390625, 958.0919189453125], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]",1

In [ ]:
sql = """
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'detectionsobserved';
"""

types_df = pd.read_sql(sql, engine)
print(types_df)

     column_name                 data_type
0           bbox                     jsonb
1       skeleton                     jsonb
2  camera_number                   integer
3      timestamp  timestamp with time zone
4   detection_id                      text
5     video_path                      text
6             id                      text